version: 2
jobs:

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t meadstats-frontend .
            docker save -o image.tar $meadstats-frontend
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  push-staging:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push staging image
          command: |
            docker load -i /tmp/workspace/image.tar
            echo ${REGISTRY_PASSWORD} | docker login ${REGISTRY_URL} --username ${REGISTRY_USERNAME} --password-stdin
            docker tag meadstats-frontend ${REGISTRY_URL}/meadstats-frontend:latest
            docker tag meadstats-frontend ${REGISTRY_URL}/meadstats-frontend:${CIRCLE_SHA1}
            docker push ${REGISTRY_URL}/meadstats-frontend:latest
            docker push ${REGISTRY_URL}/meadstats-frontend:${CIRCLE_SHA1}

  push-release:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push release image
          command: |
            docker load -i /tmp/workspace/image.tar
            echo ${REGISTRY_PASSWORD} | docker login ${REGISTRY_URL} --username ${REGISTRY_USERNAME} --password-stdin
            docker tag meadstats-frontend ${REGISTRY_URL}/meadstats-frontend:${CIRCLE_TAG} 
            docker push ${REGISTRY_URL}/meadstats-frontend:${CIRCLE_TAG} 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Bore AI Registry
          filters:
            tags:
              only: /.*/
      - push-staging:
          context: Bore AI Registry
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - push-release:
          context: Bore AI Registry
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/