name: Docker Hub

on:
  push:
    branches:
      - master

    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push to docker hub
        uses: docker/build-push-action@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hovedbore/meadstats-frontend
          add_git_labels: true
          tags: latest
          tag_with_ref: true
